// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBlocker } from "./StorageBlocker";
import type { StorageCopiedDomain } from "./StorageCopiedDomain";
import type { StorageOperationState } from "./StorageOperationState";
import type { StoragePlanAction } from "./StoragePlanAction";

/**
 * One durable operation as it is stored and reported.
 */
export type StorageOperation = { operationId: string, action: StoragePlanAction, planDigest: string, state: StorageOperationState, runId: string | null, createdAt: number, updatedAt: number, blocker: StorageBlocker | null, copied: Array<StorageCopiedDomain>, };
