// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the connection test stopped.
 */
export type StorageCheckStage = "profile" | "credential" | "connect" | "schema" | "dataset" | "ready";
