// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Row and file counts of a home, read without copying anything.
 */
export type StorageSourceEstimate = { threads: number, sections: number, projects: number, attachments: number, queuedItems: number, goals: number, logs: number, memoryOutputs: number, boardPosts: number, rolloutFiles: number, rolloutBytes: number, };
