// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a storage operation cannot proceed. The set is stable; clients may switch on it.
 */
export type StorageBlocker = "noCandidateProfile" | "migratorCredentialMissing" | "credentialUnavailable" | "caCertificateRequired" | "unsupportedNamespace" | "connectionFailed" | "connectionTimedOut" | "schemaNeedsUpgrade" | "schemaTooNew" | "schemaInvalid" | "targetNotEmpty" | "datasetNotActivated" | "datasetMismatch" | "datasetMigrating" | "datasetRetired" | "cutoverInProgress" | "authorityInvalid" | "alreadyRemote" | "notRemote" | "sqliteHomeDiffersFromCodexHome" | "stalePlan" | "notConfirmed" | "operationConflict" | "operationNotFound" | "sourceUnreadable" | "stagingFailed" | "verificationFailed" | "storageAdminRequired" | "internal";
