// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBlocker } from "./StorageBlocker";

/**
 * What the remote dataset reported when it was reachable.
 */
export type StorageRemoteSummary = { reachable: boolean,
/**
 * `open`, `migrating` or `retired`.
 */
state: string | null, generation: number | null, datasetId: string | null, datasetMatches: boolean | null, blocker: StorageBlocker | null, };
