// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the home's authority records say.
 */
export type StorageAuthority = "unmanaged" | "local" | "remote" | "cutoverInProgress" | "invalid";
