// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBlocker } from "./StorageBlocker";
import type { StorageConnectionReport } from "./StorageConnectionReport";
import type { StoragePlanAction } from "./StoragePlanAction";
import type { StorageSourceEstimate } from "./StorageSourceEstimate";

/**
 * A preview that is either startable or lists exactly what blocks it.
 */
export type StoragePlan = { planId: string, action: StoragePlanAction,
/**
 * Changes whenever any fact behind the plan changes.
 */
digest: string, host: string,
/**
 * `endpoint:port/database/namespace`; never a credential.
 */
destination: string, localGeneration: number | null, estimate: StorageSourceEstimate | null, connection: StorageConnectionReport, blockers: Array<StorageBlocker>,
/**
 * Local writers must be stopped before the operation starts.
 */
requiresPause: boolean, };
