// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageAuthority } from "./StorageAuthority";
import type { StorageBackend } from "./StorageBackend";
import type { StorageBlocker } from "./StorageBlocker";
import type { StorageRemoteSummary } from "./StorageRemoteSummary";

/**
 * The active backend of the machine that runs this app-server.
 */
export type StorageStatus = {
/**
 * Names the machine whose storage this describes, so a client never mistakes its own host
 * for the server's.
 */
host: string, activeBackend: StorageBackend, authority: StorageAuthority, localGeneration: number | null, datasetId: string | null, remoteEverActivated: boolean, candidateConfigured: boolean, remote: StorageRemoteSummary | null, blockers: Array<StorageBlocker>, };
