// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBlocker } from "./StorageBlocker";
import type { StorageCheckStage } from "./StorageCheckStage";

export type StorageConnectionReport = { stage: StorageCheckStage, blocker: StorageBlocker | null, schemaFormat: number | null, datasetState: string | null, datasetId: string | null, generation: number | null, empty: boolean | null, };
