// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageOperation } from "./StorageOperation";

/**
 * Sent to every connected client whenever a storage operation record changes, so a front end can
 * show progress without polling. The operation record is the same one `storage/operation/read`
 * returns.
 */
export type StorageOperationUpdatedNotification = { operation: StorageOperation, };
